### PR TITLE
Messenger Attachment Improvements

### PR DESCRIPTION
**Pull request by alexdlaird**
Implemented support for attachment types other than "Image" in the Messenger objects (video, audio, file, and location). These should now work in both the Send API and in the Webhook parsing.

Updated template support so templates properly parse on the Webhook. Added receipt templates to Send API and Webhook implementation.

### CODE REVIEW

**Comment by alexdlaird** [comment]
Doh, sorry, pointed it at "master" again. This was actually branched of "dev", but GitHub won't let me change the destination branch. If you change it to "dev", your commits should disappear from the diff and there shouldn't be any conflicts.

**Comment by nbartels** [comment]
😄 No problem. I just have to cherry-pick your commit, I think this should work without any trouble ...

**Comment by alexdlaird** [comment]
Is their a projected or scheduled release date for 1.26?

**Comment by nbartels** [comment]
As soon as I finished the open 1.26.0 issues, we can release the new version.

**Comment by nbartels** [comment]
New version is released 😃

**Comment by alexdlaird** [comment]
Sweet deal, thanks! When does it show up in Maven central?

**Comment by nbartels** [comment]
I don't know the exact time a new artifact needs to be visible. But normally I publish new versions in the late evening and the next morning it's available in maven central 😄 You can already find the jar in Nexus.

**Pull request closed without merging**
