### PR TITLE
Message object should contain a "metadata" field (this is already imp…

### PR DESCRIPTION
**Pull request by alexdlaird**
…lemented on the receiving end, but it was missed on the sending side): https://developers.facebook.com/docs/messenger-platform/send-api-reference#request

### CODE REVIEW

**Comment by nbartels** [comment]
So the metdata seems to be a string that can be added to the message object and that's send back from Facebook in the webhook?

Just a short question... What about `quick_replies`. This field is missing completely?

**Comment by alexdlaird** [comment]
I haven't yet used quick_replies, so I'm not sure about them.

**Comment by alexdlaird** [comment]
But they're only on the send side. On the receive webhook side, they come in as a single message.

**Comment by alexdlaird** [comment]
I'll push an implementation for QuickReplies later today :).

**Comment by alexdlaird** [comment]
Quick replies implemented!

**Comment by nbartels** [comment]
wow, really great!

**Pull request closed without merging**
