### PR TITLE
Per documentation here: https://developers.facebook.com/docs/messenge…

### PR DESCRIPTION
**Pull request by alexdlaird**
…r-platform/send-receive-api-updates#request

is_echo flag will be added to "message" attribute. Added to codebase.

Note that to receive these echoes, your web hook must be subscribed to the "message_echoes" event (this event is already accessible via the Facebook Developer Dashboard, and these events can already be seen, the documentation simply has not yet been merged).

### CODE REVIEW

**Comment by nbartels** [comment]
Very interesting. I don't see the `message_echoes` in my Facebook App, can you tell something about the event and the flag?

**Comment by alexdlaird** [comment]
Oh, I thought they had opened it up. Perhaps is whitelisting.

Basically, the new Messenger Platform webhooks have the ability to "echo" outbound messages too. So, for instance, the purpose of the webhook is to receive messages sent from a user to a page, right? But if you have message_echos enabled, you will also receive to the webhook messages sent from the page to a user.

The obvious reason, then, that this flag is necessary is because you'd be receiving a lot of unnecessary (or duplicate, depending on your implementation) if you don't have a way to see and filter out based on this flag. Thanks!

**Comment by alexdlaird** [comment]
Are you able to see this page? https://developers.facebook.com/docs/messenger-platform/send-receive-api-updates#request

I did not implement this, but per that documentation, they are also adding a "message_reads" event, which will be triggered when a user views a message.

**Comment by alexdlaird** [comment]
Sorry, I targeted this for merge, and I just looked at the contribution guidelines and see it should target dev. This is a small enough change that it should be able to just retarget the branch when you merge it, but I'll be sure to PR to dev next time!

**Comment by nbartels** [comment]
No, the page is not available for me.

I cherry-pick your commit into dev and merge it into master with the next release. I hope this will be at last this weekend.

**Comment by nbartels** [comment]
Okay, so I modified your commit a bit and added a unittest. It's cherry-picked to dev and so I close the issue. Nevertheless it's interesting you can see a new part of the API already ;)

**Pull request closed without merging**
