### PR TITLE
Issues info

### PR DESCRIPTION
**Pull request by Vanley**
https://developers.facebook.com/docs/graph-api/changelog/version3.2#marketing-api
> New Features
We are introducing a new ads run status where a campaign, ad set, or ad can be set to WITH_ISSUES if it can't be delivered, for any reason. Together with this new run status, we introduce ISSUES_INFO, which provides more detail with the error_code that prevented your ads from delivering.
New ads run status where a campaign, ad set, or ad can be set to WITH_ISSUES if it can't be delivered for any reason.

https://developers.facebook.com/docs/marketing-api/reference/ad-campaign-group#Reading
issues_info `list<AdCampaignIssuesInfo>` https://developers.facebook.com/docs/marketing-api/reference/ad-campaign-issues-info/

https://developers.facebook.com/docs/marketing-api/reference/ad-campaign#Reading
issues_info `list<AdCampaignIssuesInfo>` https://developers.facebook.com/docs/marketing-api/reference/ad-campaign-issues-info/

https://developers.facebook.com/docs/marketing-api/reference/adgroup#Reading
issues_info `list<AdgroupIssuesInfo>` https://developers.facebook.com/docs/marketing-api/reference/adgroup-issues-info/

Duplication between issues_info on different levels but what we can do...
Changed to AbstractFacebookType as it doesn't contain id.

### CODE REVIEW

**Comment by Vanley** [comment]
sadly with previous versions of API its throwing error, so its not backward compatible.
https://developers.facebook.com/ads/blog/post/2018/11/27/with-issues-status-blog/

image

**Comment by nbartels** [comment]
That's not a problem, but I suggest to add the documentation annotation to show the users, that the field is available with a specific version.

For example like this:

```
 @Getter(onMethod = @__(@GraphAPI(since = "2.6")))
 @Setter
 @Facebook
 @GraphAPI(since = "2.6")
 private Likes likes;
```

The syntax is a bit strange, but it is needed with java 7 and lombok. So I suggest to add this with "3.2" as `since` value.

**Comment by nbartels** [comment]
BTW, maybe you can rebase your branch on the current restfb dev branch and simply use the commit 558de14. Your bid strategy commit is already in dev, so you don't need it anymore. If this is working it would be great, so I can merge your changes in dev before the 2.20.0 release 😄

**Comment by Vanley** [comment]
I added documentation annotation, but i think rebasing between forks and not enough experience with git overgrown my abilities on Friday evening :P

**Pull request closed without merging**
