### PR TITLE
#664 Added UserPermission to represent Graph API endpoint

### PR DESCRIPTION
**Pull request by anenkov**

### CODE REVIEW

**Comment by anenkov** [comment]
@nbartels I have no idea why the build failed :(

**Comment by nbartels** [comment]
you should call `mvn license:format` before committing. It adds the correct license header to all files automatically.

**Comment by nbartels** [comment]
Thanks, I'll have look at it in the evening ;)

**Comment by nbartels** [comment]
squashed and merged to dev, dev-2.0

**Pull request closed without merging**
