### PR TITLE
Location Attachment and Receipt Template Improvements; Airline Templates

### PR DESCRIPTION
**Pull request by alexdlaird**
Resolving integration issues with Location attachments and Receipt templates (based on latest documentation). Adding airline templates to webhook and send API.

Location payload: https://developers.facebook.com/docs/messenger-platform/webhook-reference/message-received#location_payload

Receipt template: https://developers.facebook.com/docs/messenger-platform/send-api-reference/receipt-template

Airline templates: https://developers.facebook.com/docs/messenger-platform/send-api-reference/airline-itinerary-template

### CODE REVIEW

**Comment by alexdlaird** [comment]
Linked issue: https://github.com/restfb/restfb/issues/500

**Comment by nbartels** [comment]
@alexdlaird you can add the license information by running `mvn license:format`. I have a git hook on my machine that prevents me from committing changes that have no license header 😄

**Comment by alexdlaird** [comment]
Are there issues? I thought I caught all of those (the CI build appears to fail if those aren't attached).

I ran that and there are no new changes to commit on my local branch, so my assumption is they're all added.

**Comment by alexdlaird** [comment]
Gotcha, I'll remember this for future reference!

**Pull request closed without merging**
