### PR TITLE
Add more ChangeValue types

### PR DESCRIPTION
**Pull request by gnagy**
FEED_COMMENT_HIDE
FEED_COMMENT_UNHIDE
FEED_PHOTO_EDITED
FEED_VIDEO_ADD

### CODE REVIEW

**Comment by gnagy** [comment]
Hi, not sure what's the proper way to contribute here, but I added a couple ChangeValue types that we came across in our project. Let me know if you have any questions or remarks.

There is a related PR #512 which made it easier for us to find out which types were not supported.

**Comment by nbartels** [comment]
Great, I'll add the change to the next release. Do you have some example Jsons?

**Comment by gnagy** [comment]
Thanks @nbartels. I have real jsons, but may have to anonymize them. Is it ok if the ids and such point nowhere? Shall I add them as comments to this PR, or as files to the repo?

Also, I may add a couple more types over the next few days that I keep finding.

**Comment by nbartels** [comment]
Yes, anonymized values are great. Please add them to the repository. There is already a name scheme and it would be great you name the jsons accordingly. https://github.com/restfb/restfb/tree/master/source/test/resources/json/webhooks

Do you open another PR as you find more types or do you add them here?

**Comment by gnagy** [comment]
Ok I will commit the Jsons as files. What's the -25 suffix after some of the file names?

I think I'll just append new types to this PR.

**Comment by nbartels** [comment]
It's the version (25 == 2.5). And I think, they not really make sense, because Facebook updates their Webhook Service as the like ;)

Add them if you like, but please don't override existing files.

**Comment by gnagy** [comment]
I added the remaining webhook types I came accross in a sample of 130.000 webhook objects.

I also took liberty in cleaning up WebhookTest.java. Subsequently I ran the parser against a dump of the 130.000 webhook objects. Seems to work ok, all types recognized.

PR ready for merge.

**Comment by nbartels** [comment]
Great. I merge your pr hopefully in the next hours.

**Comment by nbartels** [comment]
I just reviewed the changes and really like that the unit tests are shorter now and have less code duplications. Great work!

**Pull request closed without merging**
